# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins
#
# Please find additional hints for individual trigger use case
# configuration options inline this script below.
#
---
name: cd
on:
  workflow_dispatch:
    inputs:
      validate_only:
        required: false
        type: boolean
        description: |
          Run validation with release drafter only
          → Skip the release job
        # Note: Change this default to true,
        #       if the checkbox should be checked by default.
        default: false
  # If you don't want any automatic trigger in general, then
  # the following check_run trigger lines should all be commented.
  # Note: Consider the use case #2 config for 'validate_only' below
  #       as an alternative option!
  check_run:
    types:
      - completed

permissions:
  checks: read
  contents: write

jobs:
  maven-cd:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
